---
- name: Ensure java is installed
  apt:
    name: openjdk-17-jre-headless
    state: present
  tags:
    - role::minecraft

- name: Set up minecraft server
  import_role:
    name: minecraft_systemd
  tags:
    - role::minecraft

- name: Ensure our voicechat config folder exists
  file:
    path: "{{ minecraft_server_root }}/{{ minecraft_server_name }}/config/voicechat"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    state: directory
    mode: "0755"
  when: minecraft_mod_voicechat_enable

- name: Ensure voicechat-server.properties is set correctly
  template:
    src: templates/voicechat-server.properties.j2
    dest: "{{ minecraft_server_root }}/{{ minecraft_server_name }}/config/voicechat/voicechat-server.properties.ansible"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: "0644"
  notify:
    - restart minecraft
  when: minecraft_mod_voicechat_enable
