---
- name: Ensure package is installed
  apt:
    name: restic
    state: present
  tags:
    - role::restic

- name: Ensure autorestic is installed
  stat:
    path: /usr/local/bin/autorestic
    checksum_algorithm: sha256
    get_checksum: true
  register: autorestic_stat
  tags:
    - role::restic

- name: Install autorestic
  include_tasks: setup.yml
  when: not autorestic_stat.stat.exists or not autorestic_stat.stat.checksum == '5e560bb15afa317707d919dde076ac433887124c38c777a0c4fd66492293f426'
  tags:
    - role::restic
