- name: Update hostname to match Ansible inventory
  hostname:
    name: "{{ inventory_hostname }}"
  tags:
    - role::common

- name: Update /etc/hosts to match Ansible inventory
  template:
    src: etc-hosts.j2
    dest: /etc/hosts
    mode: "0644"
    owner: root
    group: root
  tags:
    - role::common

- name: Disable SSH password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify:
    - restart ssh
  tags:
    - role::common

- name: Set timezone to UTC
  timezone:
    name: Etc/UTC
  tags:
    - role::common
